/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hu.webtown.liferay.invention.ideas.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the InventionIdeaInstance service. Represents a row in the &quot;le_demo_InventionIdeaInstance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link hu.webtown.liferay.invention.ideas.model.impl.InventionIdeaInstanceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link hu.webtown.liferay.invention.ideas.model.impl.InventionIdeaInstanceImpl}.
 * </p>
 *
 * @author lehel
 * @see InventionIdeaInstance
 * @see hu.webtown.liferay.invention.ideas.model.impl.InventionIdeaInstanceImpl
 * @see hu.webtown.liferay.invention.ideas.model.impl.InventionIdeaInstanceModelImpl
 * @generated
 */
@ProviderType
public interface InventionIdeaInstanceModel extends BaseModel<InventionIdeaInstance>,
	GroupedModel, ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a invention idea instance model instance should use the {@link InventionIdeaInstance} interface instead.
	 */

	/**
	 * Returns the primary key of this invention idea instance.
	 *
	 * @return the primary key of this invention idea instance
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this invention idea instance.
	 *
	 * @param primaryKey the primary key of this invention idea instance
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this invention idea instance.
	 *
	 * @return the uuid of this invention idea instance
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this invention idea instance.
	 *
	 * @param uuid the uuid of this invention idea instance
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this invention idea instance.
	 *
	 * @return the ID of this invention idea instance
	 */
	public long getId();

	/**
	 * Sets the ID of this invention idea instance.
	 *
	 * @param id the ID of this invention idea instance
	 */
	public void setId(long id);

	/**
	 * Returns the group ID of this invention idea instance.
	 *
	 * @return the group ID of this invention idea instance
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this invention idea instance.
	 *
	 * @param groupId the group ID of this invention idea instance
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this invention idea instance.
	 *
	 * @return the company ID of this invention idea instance
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this invention idea instance.
	 *
	 * @param companyId the company ID of this invention idea instance
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this invention idea instance.
	 *
	 * @return the user ID of this invention idea instance
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this invention idea instance.
	 *
	 * @param userId the user ID of this invention idea instance
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this invention idea instance.
	 *
	 * @return the user uuid of this invention idea instance
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this invention idea instance.
	 *
	 * @param userUuid the user uuid of this invention idea instance
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this invention idea instance.
	 *
	 * @return the user name of this invention idea instance
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this invention idea instance.
	 *
	 * @param userName the user name of this invention idea instance
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this invention idea instance.
	 *
	 * @return the create date of this invention idea instance
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this invention idea instance.
	 *
	 * @param createDate the create date of this invention idea instance
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this invention idea instance.
	 *
	 * @return the modified date of this invention idea instance
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this invention idea instance.
	 *
	 * @param modifiedDate the modified date of this invention idea instance
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this invention idea instance.
	 *
	 * @return the name of this invention idea instance
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this invention idea instance.
	 *
	 * @param name the name of this invention idea instance
	 */
	public void setName(String name);

	/**
	 * Returns the inventor name of this invention idea instance.
	 *
	 * @return the inventor name of this invention idea instance
	 */
	@AutoEscape
	public String getInventorName();

	/**
	 * Sets the inventor name of this invention idea instance.
	 *
	 * @param inventorName the inventor name of this invention idea instance
	 */
	public void setInventorName(String inventorName);

	/**
	 * Returns the short description of this invention idea instance.
	 *
	 * @return the short description of this invention idea instance
	 */
	@AutoEscape
	public String getShortDescription();

	/**
	 * Sets the short description of this invention idea instance.
	 *
	 * @param shortDescription the short description of this invention idea instance
	 */
	public void setShortDescription(String shortDescription);

	/**
	 * Returns the description of this invention idea instance.
	 *
	 * @return the description of this invention idea instance
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this invention idea instance.
	 *
	 * @param description the description of this invention idea instance
	 */
	public void setDescription(String description);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(InventionIdeaInstance inventionIdeaInstance);

	@Override
	public int hashCode();

	@Override
	public CacheModel<InventionIdeaInstance> toCacheModel();

	@Override
	public InventionIdeaInstance toEscapedModel();

	@Override
	public InventionIdeaInstance toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}